selectors = {
    'base_url': "https://iowagirleats.com/",
    'search_page': '?s=',
    'listed_recipe': '.post-summary__title a',
    'title': '.recipe__title',
    'description': '',
    'image': '.post-detail__content img',
    'prep_time': '',
    'cook_time': '',
    'total_time': '',
    'servings': '',
    'ingredients': '.recipe-ingredients li',
    'directions': '.recipe-directions li',
    'notes': '.recipe-tips',
}