selectors = {
    'base_url': "",
    'search_page': '',
    'listed_recipe': '',
    'title': '',
    'description': '',
    'image': '',
    'prep_time': '',
    'cook_time': '',
    'total_time': '',
    'servings': '',
    'ingredients': '',
    'directions': '',
    'notes': '',
}